# Cloud Build configuration for development/staging deployment
# Lighter weight version for non-production branches

substitutions:
  _SERVICE_NAME: verbio-backend-dev
  _REGION: us-central1
  _IMAGE_NAME: verbio-backend-dev
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '1Gi'
  _CPU: '1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BRANCH_NAME-$SHORT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
    id: 'build-image'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BRANCH_NAME-$SHORT_SHA'
    id: 'push-image'

  # Step 3: Deploy to Cloud Run (dev environment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying to development environment..."

        gcloud run deploy ${_SERVICE_NAME} \
          --image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BRANCH_NAME-$SHORT_SHA \
          --platform=managed \
          --region=${_REGION} \
          --allow-unauthenticated \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --timeout=60 \
          --concurrency=100 \
          --port=8080 \
          --set-env-vars="NODE_ENV=development" \
          --set-env-vars="PORT=8080" \
          --set-env-vars="LOG_LEVEL=debug" \
          --set-env-vars="BRANCH=$BRANCH_NAME" \
          --set-env-vars="COMMIT_SHA=$SHORT_SHA" \
          --update-labels="environment=development,branch=$BRANCH_NAME,version=$SHORT_SHA"

        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "✅ Development deployment completed"
        echo "🌐 Service URL: $SERVICE_URL"
    id: 'deploy-dev'

timeout: '900s'  # 15 minutes

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BRANCH_NAME-$SHORT_SHA'